---
- name: get hcloud api key from environment
  set_fact:
    hcloud_api_token: "{{ lookup('env', 'HCLOUD_API_TOKEN') }}"

- name: determine configuration for hcloud server
  include: tasks/configuration.yml

- name: Create a basic server with ssh key
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_api_token }}"
    name: "{{ config.name }}"
    server_type: "{{ config.server.server_type }}"
    image: "{{ config.server.image }}"
    location: "{{ config.server.location }}"
    ssh_keys: "{{ config.server.initial_ssh_key_names }}"
    labels: "{{ hcloud_server_labels }}"
    state: "{{ hcloud_server_state }}"
  register: hcloud_server

- name: extract hcloud server info
  set_fact:
    hcloud_server: "{{ hcloud_server.hcloud_server }}"

- name: add server to the inventory
  include: tasks/inventory.yml
