---
- name: get cloudflare api key from environment
  set_fact:
    cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
  when: config.domains | length > 0

- name: get server ip
  set_fact:
    server_ip: "{{ hostvars[config.name].ansible_ssh_host }}"

- name: loop over domains
  include_tasks: tasks/domain.yml
  with_items: "{{ config.domains }}"
  loop_control:
    loop_var: domain
  when: config.domains | length > 0
