---
- include_tasks: tasks/ubuntu.yml
- include_tasks: tasks/docker.yml
- include_tasks: tasks/users.yml
- include_tasks: tasks/ssh-authorization.yml
- include_tasks: tasks/firewall.yml
- include_tasks: tasks/os-hardening.yml
- include_tasks: tasks/ssh-hardening.yml
