---
- name: check if carry path archive exists
  stat:
    path: "/tmp/{{ ansible_hostname }}{{ carry_path }}/archive.gz"
  register: archive

- name: ensure path restore path exists
  file:
    path: "{{ carry_path }}"
    state: directory
  become: yes
  when: archive.stat.exists

- name: restore 
  ansible.builtin.unarchive:
    src: "/tmp/{{ ansible_hostname }}{{ carry_path }}/archive.gz"
    dest: "{{ carry_path }}"
  become: yes
  ignore_errors: yes # Empty archive files are not supported.
  when: archive.stat.exists